<?php
  /**
   *     @file
   *  Helps site builders and module developers investigate a site.
   *
   */

  /*
   *
   *  Implements hook_form_alter() to show each form's identifier.
   *  Secondary, implements the debug function.
   */
  function xray_form_alter(&$form, &$form_state, $form_id) {
    $form['xray_display_form_id'] = array(
      '#type' => 'item',
      '#title' => t('Internal Form ID'),
      '#markup' => $form_id,
      '#theme-attributes' => array('container__xray__form'),
      '#attributes' => array('class' => array('xray')),
      '#weight' => -100,
    );
  }
  /**
   *
   * Implements hook_help()
   *
   */
  function xray_help($path, $arg) {
    if ($path == 'admin/structure') {
      return t('This site has stuff!');
    }
    switch ($path) {
        case 'admin/appearance':
            return _xray_help_admin_appearance();
    }
  }
    /**
   *
   * Fetch information about themes
   *
   */
  function xray_stats_enabled_themes() {
    $themes = list_themes();
    $num_themes = count($themes);
    //Initialize variables for the data you will collect.
    $num_hidden = 0; //Number of hidden themes.
    $num_enabled = 0;
    $summaries = array();
    //Iterate through each theme, gathering data that you care about.
    foreach ($thmes as $themename => $theme) {
        // Do not gather statistics for hidden themes, but keep a count of them.
        if (isset($theme->info['hidden']) && $theme->info['hidden']) {
            $num_hidden++;
        }
        else { //This is a visible theme.
            if ($theme->status) {
                $num_enabled++;
                //This is an enabled theme, provide more stats.
                $summaries[$theme->info['name']] = array(
                    'regions' => count($theme->info['regions']),
                    'overlay_regions' => count($theme->info['overlay_regions']),
                    'regions_hidden' => count($theme->info['overlay_regions']),
                    'features' => count($theme->info['features']),
                    'kindsofstylesheets' => count($theme->info['stylesheets']),
                    'allstylesheets' => isset($theme->info['stylesheets']['all']) ? count($theme->info['stylesheets']['all']) : 0
                );
            }
        }
    }
  }
    
    /**
   *
   * Hep text for the admin/appearance page.
   *
   */
  function _xray_help_admin_appearance() {
    $output = '';
    $data = xray_stats_enabled_themes();
    $output .= format_plural(
        $data['num_hidden'],
        'There is one hidden theme.',
        'There are @count hidden themes.'        
    );
    return theme('xray_help', array('text' => $output));
  }


  