<?php

  /* This tells the entire Drupal site that we are using the jQuery UI for
  *    whatever 'action' is about to fire.
  *  In this example, we're firing the "toggle" function.
  */  
  
  /*
  *  If browser sees a link somewhere in a div, box it, toss it, and throw it out
  *    on a boxed overlay.  This 'action' should even fire on hidden elements.
  *    Will test later.  Think survey question pop-ups.
  *
  *  
  *    
  */
   
  

  


?>